language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
git:
    depth: 1
script:
    - python -c "import sqlmap; import sqlmapapi"
    - python sqlmap.py --smoke
    - python sqlmap.py --vuln
